# Generated by Django 5.1 on 2024-08-31 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('efectivo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tarjeta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('numero_orden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno_abierto', models.BooleanField(default=True)),
                ('fondo_caja', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('numero_ordenes', models.IntegerField()),
                ('fecha_cierre', models.DateTimeField()),
                ('total_efectivo', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ManyToManyField(to='productos.productos')),
                ('id_orden', models.ManyToManyField(to='caja.orden')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='id_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='caja.turno'),
        ),
    ]
