# Generated by Django 5.1 on 2024-09-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='numero_ordenes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
