# Generated by Django 5.1 on 2024-09-04 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_orden_total_alter_orden_efectivo_alter_orden_tarjeta'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Orden'},
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='id_orden',
        ),
        migrations.RemoveField(
            model_name='detalleorden',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caja.orden'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.productos'),
        ),
    ]
